import './CharacterSelect.css'
import { CharacterIDCard } from './CharacterIDCard'
import { OperatorClassSelect } from './OperatorClassSelect'

export function CharacterSelectUI() {
    return (
        <>
            <div className="mainBody">
                <OperatorClassSelect />
                <div id="OpCharSelect">
                    <CharacterIDCard name="Aak"/>
                    <CharacterIDCard name="Angelina"/>
                    <CharacterIDCard name="Angelina"/>
                    <CharacterIDCard name="Archetto"/>
                    <CharacterIDCard name="Ash"/>
                    <CharacterIDCard name="Bagpipe"/>
                    <CharacterIDCard name="Blaze"/>
                    <CharacterIDCard name="Blemishine"/>
                    <CharacterIDCard name="Carnelian"/>
                    <CharacterIDCard name="Ceobe"/>
                    <CharacterIDCard name="Ch'en"/>
                    <CharacterIDCard name="Ch'en the Holunday"/>
                    <CharacterIDCard name="Chongyue"/>
                    <CharacterIDCard name="Dorothy"/>
                    <CharacterIDCard name="Dusk"/>
                    <CharacterIDCard name="Ebenholz"/>
                    <CharacterIDCard name="Euncectes"/>
                    <CharacterIDCard name="Exusiai"/>
                    <CharacterIDCard name="Eyjafjalla"/>
                    <CharacterIDCard name="Fartooth"/>
                    <CharacterIDCard name="Fiammetta"/>
                    <CharacterIDCard name="Flametail"/>
                    <CharacterIDCard name="Gavial the Invincible"/>
                    <CharacterIDCard name="Gladiia"/>
                    <CharacterIDCard name="Gnosis"/>
                    <CharacterIDCard name="Goldenglow"/>
                    <CharacterIDCard name="Hellagur"/>
                    <CharacterIDCard name="Horn"/>
                    <CharacterIDCard name="Hoshiguma"/>
                    <CharacterIDCard name="Ifrit"/>
                    <CharacterIDCard name="Irene"/>
                    <CharacterIDCard name="Kal'tsit"/>
                    <CharacterIDCard name="Kirin R Yato"/>
                    <CharacterIDCard name="Lee"/>
                    <CharacterIDCard name="Lin"/>
                    <CharacterIDCard name="Ling"/>
                    <CharacterIDCard name="Lumen"/>
                    <CharacterIDCard name="Magallan"/>
                    <CharacterIDCard name="Mizuki"/>
                    <CharacterIDCard name="Mostima"/>
                    <CharacterIDCard name="Mountain"/>
                    <CharacterIDCard name="Mudrock"/>
                    <CharacterIDCard name="Mlynar"/>
                    <CharacterIDCard name="Nearl the Radiant Knight"/>
                    <CharacterIDCard name="Nian"/>
                    <CharacterIDCard name="Nightingale"/>
                    <CharacterIDCard name="Pallas"/>
                    <CharacterIDCard name="Passenger"/>
                    <CharacterIDCard name="Penance"/>
                    <CharacterIDCard name="Phantom"/>
                    <CharacterIDCard name="Quibai"/>
                    <CharacterIDCard name="Reed theFlame Shadow"/>
                    <CharacterIDCard name="Rosmontis"/>
                    <CharacterIDCard name="Saga"/>
                    <CharacterIDCard name="Saileach"/>
                    <CharacterIDCard name="Saria"/>
                    <CharacterIDCard name="Schwarz"/>
                    <CharacterIDCard name="Shining"/>
                    <CharacterIDCard name="Seige"/>
                    <CharacterIDCard name="SilverAsh"/>
                    <CharacterIDCard name="Skadi"/>
                    <CharacterIDCard name="Skadi the Corrupting Heart"/>
                    <CharacterIDCard name="Specter the Unchained"/>
                    <CharacterIDCard name="Stainless"/>
                    <CharacterIDCard name="Surtr"/>
                    <CharacterIDCard name="Suzuran"/>
                    <CharacterIDCard name="Texas theOmertosa"/>
                    <CharacterIDCard name="Thorns"/> 
                    <CharacterIDCard name="Vigil"/>
                    <CharacterIDCard name="W"/>
                    <CharacterIDCard name="Weedy"/>
                    <CharacterIDCard name="Pozyomka"/>
                    <CharacterIDCard name="Rosa"/>

                    <CharacterIDCard name="Absinthe"/>
                    <CharacterIDCard name="Akafuyu"/>
                    <CharacterIDCard name="Amiya"/>
                    <CharacterIDCard name="Andreana"/>
                    <CharacterIDCard name="Aosta"/>
                    <CharacterIDCard name="Aosta"/>
                    <CharacterIDCard name="April"/>
                    <CharacterIDCard name="Asbestos"/>
                    <CharacterIDCard name="Ashlock"/>
                    <CharacterIDCard name="Astesia"/>
                    <CharacterIDCard name="Astgenne"/>
                    <CharacterIDCard name="Aurora"/>
                    <CharacterIDCard name="Ayerscarpe"/>
                    <CharacterIDCard name="Beeswax"/>
                    <CharacterIDCard name="Bena"/>
                    <CharacterIDCard name="Bibeak"/>
                    <CharacterIDCard name="Bison"/>
                    <CharacterIDCard name="Blackknight"/>
                    <CharacterIDCard name="Blitz"/>
                    <CharacterIDCard name="Blue Poison"/>
                    <CharacterIDCard name="Breeze"/>
                    <CharacterIDCard name="Broca"/>
                    <CharacterIDCard name="Cantabile"/>
                    <CharacterIDCard name="Ceylon"/>
                    <CharacterIDCard name="Chiave"/>
                    <CharacterIDCard name="Cliffheart"/>
                    <CharacterIDCard name="Corroserum"/>
                    <CharacterIDCard name="Croissant"/>
                    <CharacterIDCard name="Czerny"/>
                    <CharacterIDCard name="Dagda"/>
                    <CharacterIDCard name="Elysium"/>
                    <CharacterIDCard name="Enforcer"/>
                    <CharacterIDCard name="Erato"/>
                    <CharacterIDCard name="Executor"/>
                    <CharacterIDCard name="FEater"/>
                    <CharacterIDCard name="Firewatch"/>
                    <CharacterIDCard name="Firewhistle"/>
                    <CharacterIDCard name="Flamebr /inger"/>
                    <CharacterIDCard name="Flint"/>
                    <CharacterIDCard name="Folinic"/>
                    <CharacterIDCard name="Franka"/>
                    <CharacterIDCard name="Frost"/>
                    <CharacterIDCard name="Glaucus"/>
                    <CharacterIDCard name="Grani"/>
                    <CharacterIDCard name="GreyThroat"/>
                    <CharacterIDCard name="Greyy the Lighningbearer"/>
                    <CharacterIDCard name="Harmonie"/>
                    <CharacterIDCard name="Heidi"/>
                    <CharacterIDCard name="Hibiscus the Purifier"/>
                    <CharacterIDCard name="Highmore"/>
                    <CharacterIDCard name="Honeyberry"/>
                    <CharacterIDCard name="Hung"/>
                    <CharacterIDCard name="Indra"/>
                    <CharacterIDCard name="Iris"/>
                    <CharacterIDCard name="Jieyun"/>
                    <CharacterIDCard name="Kafka"/>
                    <CharacterIDCard name="Kazemaru"/>
                    <CharacterIDCard name="Kirara"/>
                    <CharacterIDCard name="Kjera"/>
                    <CharacterIDCard name="Kroos the Keen Glint"/>
                    <CharacterIDCard name="La Pluma"/>
                    <CharacterIDCard name="Lava the Purgatory"/>
                    <CharacterIDCard name="Leizi"/>
                    <CharacterIDCard name="Leonhardt"/>
                    <CharacterIDCard name="Liskarm"/>
                    <CharacterIDCard name="Lunacub"/>
                    <CharacterIDCard name="Manticore"/>
                    <CharacterIDCard name="Mayer"/>
                    <CharacterIDCard name="Melanite"/>
                    <CharacterIDCard name="Metoerite"/>
                    <CharacterIDCard name="Minimalist"/>
                    <CharacterIDCard name="Mint"/>
                    <CharacterIDCard name="Morgan"/>
                    <CharacterIDCard name="Mr. Nothing"/>
                    <CharacterIDCard name="Mulberry"/>
                    <CharacterIDCard name="Nearl"/>
                    <CharacterIDCard name="Nightmare"/>
                    <CharacterIDCard name="Nine-Colored Deer"/>
                    <CharacterIDCard name="Paprika"/>
                    <CharacterIDCard name="Platinum"/>
                    <CharacterIDCard name="Pramanix"/>
                    <CharacterIDCard name="Projekt Red"/>
                    <CharacterIDCard name="Provence"/>
                    <CharacterIDCard name="Proviso"/>
                    <CharacterIDCard name="Ptilopsis"/>
                    <CharacterIDCard name="Puzzle"/>
                    <CharacterIDCard name="Qanipalaat"/>
                    <CharacterIDCard name="Quercus"/>
                    <CharacterIDCard name="Rathalos S Noir Corne"/>
                    <CharacterIDCard name="Reed"/>
                    <CharacterIDCard name="Robin"/>
                    <CharacterIDCard name="Rockrock"/>
                    <CharacterIDCard name="Santalla"/>
                    <CharacterIDCard name="Savage"/>
                    <CharacterIDCard name="Scene"/>
                    <CharacterIDCard name="Sesa"/>
                    <CharacterIDCard name="Shalem"/>
                    <CharacterIDCard name="Shamare"/>
                    <CharacterIDCard name="Sideroca"/>
                    <CharacterIDCard name="Silence"/>
                    <CharacterIDCard name="Skyfire"/>
                    <CharacterIDCard name="Snowsant"/>
                    <CharacterIDCard name="Sora"/>
                    <CharacterIDCard name="Specter"/>
                    <CharacterIDCard name="Swire"/>
                    <CharacterIDCard name="Tachanka"/>
                    <CharacterIDCard name="Tequila"/>
                    <CharacterIDCard name="Texas"/>
                    <CharacterIDCard name="Toddifons"/>
                    <CharacterIDCard name="Tomimi"/>
                    <CharacterIDCard name="Tsukinogi"/>
                    <CharacterIDCard name="Tuyue"/>
                    <CharacterIDCard name="Vulcan"/>
                    <CharacterIDCard name="Waai Fu"/>
                    <CharacterIDCard name="Warfarin"/>
                    <CharacterIDCard name="Whislash"/>
                    <CharacterIDCard name="Whisperain"/>
                    <CharacterIDCard name="Wild Mane"/>
                    <CharacterIDCard name="Wind Chimes"/>
                    <CharacterIDCard name="Windflit"/>
                    <CharacterIDCard name="Zima"/>
                    <CharacterIDCard name="Istina"/>

                    <CharacterIDCard name="Acipddrop"/>
                    <CharacterIDCard name="Ambirel"/>
                    <CharacterIDCard name="Arene"/>
                    <CharacterIDCard name="Beanstalk"/>
                    <CharacterIDCard name="Beehunter"/>
                    <CharacterIDCard name="Bubble"/>
                    <CharacterIDCard name="Chestnut"/>
                    <CharacterIDCard name="Click"/>
                    <CharacterIDCard name="Convinction"/>
                    <CharacterIDCard name="Courier"/>
                    <CharacterIDCard name="Cuora"/>
                    <CharacterIDCard name="Cutter"/>
                    <CharacterIDCard name="Deepcolor"/>
                    <CharacterIDCard name="Dobermann"/>
                    <CharacterIDCard name="Dur-Nar"/>
                    <CharacterIDCard name="Earthspirit"/>
                    <CharacterIDCard name="Estelle"/>
                    <CharacterIDCard name="Ethan"/>
                    <CharacterIDCard name="Frostleaf"/>
                    <CharacterIDCard name="Gavial"/>
                    <CharacterIDCard name="Gitano"/>
                    <CharacterIDCard name="Gravel"/>
                    <CharacterIDCard name="Greyy"/>
                    <CharacterIDCard name="Haze"/>
                    <CharacterIDCard name="Indigo"/>
                    <CharacterIDCard name="Jackie"/>
                    <CharacterIDCard name="Jaye"/>
                    <CharacterIDCard name="Jessica"/>
                    <CharacterIDCard name="Luo Xiaohei"/>
                    <CharacterIDCard name="Matoimaru"/>
                    <CharacterIDCard name="Matterhorn"/>
                    <CharacterIDCard name="May"/>
                    <CharacterIDCard name="Meteor"/>
                    <CharacterIDCard name="Mousse"/>
                    <CharacterIDCard name="Myrrh"/>
                    <CharacterIDCard name="Myrtle"/>
                    <CharacterIDCard name="Perfumer"/>
                    <CharacterIDCard name="Pinecone"/>
                    <CharacterIDCard name="Podenco"/>
                    <CharacterIDCard name="Pudding"/>
                    <CharacterIDCard name="Purestream"/>
                    <CharacterIDCard name="Quartz"/>
                    <CharacterIDCard name="Roberta"/>
                    <CharacterIDCard name="Rope"/>
                    <CharacterIDCard name="Scavenger"/>
                    <CharacterIDCard name="Shaw"/>
                    <CharacterIDCard name="ShiraYuki"/>
                    <CharacterIDCard name="Sussurro"/>
                    <CharacterIDCard name="Totter"/>
                    <CharacterIDCard name="Utage"/>
                    <CharacterIDCard name="Vermeil"/>
                    <CharacterIDCard name="Vigna"/>
                    <CharacterIDCard name="Gummy"/>
                    
                </div>
            </div>
        </>)
}